pub(crate) const PAYLOAD_ELF: &[u8] = include_bytes!(env!("XV6_PAYLOAD_ELF"));
pub(crate) const FS_SERVER_ELF: &[u8] = include_bytes!(env!("XV6_FS_SERVER_ELF"));
pub(crate) const DISK_SERVER_ELF: &[u8] = include_bytes!(env!("XV6_DISK_SERVER_ELF"));
pub(crate) const ROOT_IS_INIT: bool = option_env!("XV6_COMPILED_ROOT_IS_INIT").is_some();
pub(crate) const CONSOLE_INPUT: &[u8] = match option_env!("XV6_CONSOLE_INPUT") {
    Some(input) => input.as_bytes(),
    None => b"",
};

pub(crate) use sel4_user::{
    FAULT_UNKNOWN_SYSCALL, FAULT_VM_FAULT, INIT_ASID_POOL, INIT_TCB, INIT_VSPACE, IRQ_CONTROL,
    KERNEL_TIMER_IRQ, LABEL_CNODE_COPY, LABEL_CNODE_DELETE, LABEL_CNODE_MINT, LABEL_CNODE_REVOKE,
    LABEL_CNODE_SAVE_CALLER, LABEL_IRQ_ISSUE_IRQ_HANDLER, LABEL_IRQ_SET_NOTIFICATION,
    LABEL_RISCV_ASID_POOL_ASSIGN, LABEL_RISCV_PAGE_GET_ADDRESS, LABEL_RISCV_PAGE_MAP,
    LABEL_RISCV_PAGE_UNMAP, LABEL_TCB_BIND_NOTIFICATION, LABEL_TCB_CONFIGURE,
    LABEL_TCB_READ_REGISTERS, LABEL_TCB_SET_PRIORITY, LABEL_TCB_SUSPEND, LABEL_TCB_WRITE_REGISTERS,
    LABEL_UNTYPED_RETYPE, OBJ_4K, OBJ_CAP_TABLE, OBJ_ENDPOINT, OBJ_NOTIFICATION, OBJ_PAGE_TABLE,
    OBJ_TCB, OBJ_UNTYPED, PAGE_SIZE, ROOT_CNODE, ROOT_CNODE_DEPTH, WORD_BITS,
};

pub(crate) const CHILD_CNODE_BITS: u64 = 8;
pub(crate) const CHILD_FAULT_EP: u64 = 1;
pub(crate) const CHILD_IPC_BUFFER: u64 = 0x7000_0000;
pub(crate) const CHILD_STACK_PAGES: usize = 1;
pub(crate) const XV6_MAXVA: u64 = 1 << (9 + 9 + 9 + 12 - 1);
pub(crate) const XV6_TRAMPOLINE: u64 = XV6_MAXVA - PAGE_SIZE;
pub(crate) const XV6_TRAPFRAME: u64 = XV6_TRAMPOLINE - PAGE_SIZE;
pub(crate) const CHILD_HEAP_LIMIT: u64 = XV6_TRAPFRAME;
pub(crate) const HOST_ALIAS_BASE: u64 = 0x4000_0000;
pub(crate) const MAX_MAPPINGS: usize = 8192;
pub(crate) const FRAME_POOL_CAP: usize = MAX_MAPPINGS;
pub(crate) const SBRK_MAPPING_HEADROOM: usize = 256;
pub(crate) const SBRK_EAGER_MAP_LIMIT: usize = 64;
pub(crate) const SPARSE_EAGER_RESERVE_LIMIT: u64 = 512 * 1024 * 1024;
pub(crate) const FORK_SLOT_HEADROOM: usize = 32;
pub(crate) const MAX_RECYCLED_SLOTS: usize = MAX_MAPPINGS * 2;
pub(crate) const MAX_PROCS: usize = 16;
pub(crate) const PROCESS_UNTYPED_BITS: u64 = 25;
pub(crate) const PROCESS_UNTYPED_PARENT_BITS: u8 = 29;
pub(crate) const PROC_UNUSED: u8 = 0;
pub(crate) const PROC_RUNNABLE: u8 = 1;
pub(crate) const PROC_ZOMBIE: u8 = 2;
pub(crate) const PROC_WAITING: u8 = 3;
pub(crate) const PROC_PIPE_WRITE: u8 = 4;
pub(crate) const PROC_PIPE_READ: u8 = 5;
pub(crate) const SERVICE_UNTYPED_BITS: u64 = 22;
pub(crate) const FS_SERVER_PROC_SLOT: usize = MAX_PROCS;
pub(crate) const DISK_SERVER_PROC_SLOT: usize = MAX_PROCS + 1;
pub(crate) const FS_SERVER_PID: u64 = 0xffff_0001;
pub(crate) const DISK_SERVER_PID: u64 = 0xffff_0002;

pub(crate) const FD_CLOSED: u8 = 0;
pub(crate) const FD_CONSOLE: u8 = 1;
pub(crate) const FD_PIPE_READ: u8 = 4;
pub(crate) const FD_PIPE_WRITE: u8 = 5;
pub(crate) const FD_FS_SERVER_FILE: u8 = 6;
pub(crate) const FD_FS_SERVER_DIR: u8 = 7;

pub(crate) const SBRK_EAGER: u64 = 1;
pub(crate) const SBRK_LAZY: u64 = 2;

pub(crate) use xv6_abi::{
    CONSOLE_INO, FS_BLOCK_SIZE, FS_OP_CHDIR, FS_OP_CLOSE, FS_OP_FSTAT, FS_OP_INIT, FS_OP_LINK,
    FS_OP_MKDIR, FS_OP_MKNOD, FS_OP_OPEN, FS_OP_READ, FS_OP_READDIR, FS_OP_UNLINK, FS_OP_WRITE,
    MAX_EXEC_ARG_LEN, MAX_EXEC_ARGS, MAX_FD, MAX_FILE_BYTES, MAX_OPEN_FILES, MAX_PIPES, O_CREATE,
    O_RDWR, O_TRUNC, O_WRONLY, PIPE_BUF, ROOT_INO, SYS_CHDIR, SYS_CLOSE, SYS_DUP, SYS_EXEC,
    SYS_EXIT, SYS_FORK, SYS_FSTAT, SYS_GETPID, SYS_KILL, SYS_LINK, SYS_MKDIR, SYS_MKNOD, SYS_OPEN,
    SYS_PAUSE, SYS_PIPE, SYS_READ, SYS_SBRK, SYS_UNLINK, SYS_UPTIME, SYS_WAIT, SYS_WRITE, T_DEVICE,
    T_DIR, T_FILE, VIRTIO_BLK_SECTOR_SIZE, VIRTIO_MMIO_BASE, VIRTIO_MMIO_SIZE, XV6_ABI_VERSION,
    XV6_DISK_ENDPOINT_CPTR, XV6_DISK_SERVER_BADGE, XV6_DISK_SHARED_BUFFER_VADDR,
    XV6_FS_SERVER_BADGE, XV6_HOST_TO_FS_PROTOCOL, XV6_OK, XV6_SERVICE_ENDPOINT_CPTR,
    XV6_VIRTIO_DMA_VADDR, XV6_VIRTIO_MMIO_VADDR,
};
