#![allow(unused_imports)]

pub(crate) const UART_SERVER_ELF: &[u8] = include_bytes!(env!("LINUX_UART_SERVER_ELF"));
pub(crate) const VFS_SERVER_ELF: &[u8] = include_bytes!(env!("LINUX_VFS_SERVER_ELF"));

pub(crate) use sel4_user::{
    FAULT_UNKNOWN_SYSCALL, FAULT_VM_FAULT, INIT_ASID_POOL, INIT_TCB, INIT_VSPACE, IRQ_CONTROL,
    KERNEL_TIMER_IRQ, LABEL_ASID_POOL_ASSIGN, LABEL_CNODE_COPY, LABEL_CNODE_DELETE,
    LABEL_CNODE_MINT, LABEL_CNODE_REVOKE, LABEL_IRQ_ISSUE_IRQ_HANDLER, LABEL_IRQ_SET_NOTIFICATION,
    LABEL_PAGE_DIRECTORY_MAP, LABEL_PAGE_GET_ADDRESS, LABEL_PAGE_MAP, LABEL_PAGE_TABLE_MAP,
    LABEL_PAGE_UNMAP, LABEL_PDPT_MAP, LABEL_TCB_BIND_NOTIFICATION, LABEL_TCB_CONFIGURE,
    LABEL_TCB_READ_REGISTERS, LABEL_TCB_SET_SCHED_PARAMS, LABEL_TCB_SUSPEND,
    LABEL_TCB_WRITE_REGISTERS, LABEL_UNTYPED_RETYPE, OBJ_4K, OBJ_CAP_TABLE, OBJ_ENDPOINT,
    OBJ_NOTIFICATION, OBJ_PAGE_DIRECTORY, OBJ_PAGE_TABLE, OBJ_PDPT, OBJ_REPLY, OBJ_TCB,
    OBJ_UNTYPED, OBJ_VSPACE, PAGE_SIZE, ROOT_CNODE, ROOT_CNODE_DEPTH, WORD_BITS,
};

pub(crate) const CHILD_CNODE_BITS: u64 = 8;
pub(crate) const CHILD_FAULT_EP: u64 = 1;
pub(crate) const CHILD_IPC_BUFFER: u64 = 0x7000_0000;
pub(crate) const CHILD_STACK_PAGES: usize = 16;
pub(crate) const SERVICE_STACK_PAGES: usize = 16;
#[cfg(target_arch = "x86_64")]
pub(crate) const USER_MAXVA: u64 = 1 << 47;
#[cfg(not(target_arch = "x86_64"))]
pub(crate) const USER_MAXVA: u64 = 1 << (9 + 9 + 9 + 12 - 1);
pub(crate) const USER_TRAMPOLINE: u64 = USER_MAXVA - PAGE_SIZE;
pub(crate) const USER_TRAPFRAME: u64 = USER_TRAMPOLINE - PAGE_SIZE;
pub(crate) const CHILD_HEAP_LIMIT: u64 = USER_TRAPFRAME;
pub(crate) const HOST_ALIAS_BASE: u64 = 0x4000_0000;
pub(crate) const MAX_MAPPINGS: usize = 4096;
pub(crate) const MAX_PAGE_TABLE_MAPPINGS: usize = MAX_MAPPINGS + MAX_PROCS * 8;
pub(crate) const FRAME_POOL_CAP: usize = MAX_MAPPINGS;
pub(crate) const SBRK_MAPPING_HEADROOM: usize = 256;
pub(crate) const SBRK_EAGER_MAP_LIMIT: usize = 64;
pub(crate) const SPARSE_EAGER_RESERVE_LIMIT: u64 = 512 * 1024 * 1024;
pub(crate) const FORK_SLOT_HEADROOM: usize = 32;
pub(crate) const MAX_RECYCLED_SLOTS: usize = MAX_MAPPINGS * 2;
pub(crate) const MAX_PROCS: usize = 64;
pub(crate) const MAX_FAULT_REPLY_CAPS: usize = MAX_PROCS + 8;
pub(crate) const PROCESS_UNTYPED_BITS: u64 = 18;
// x86 FREE_RAM is 16 MiB..512 MiB, so the largest aligned untyped is 256 MiB.
#[cfg(target_arch = "x86_64")]
pub(crate) const PROCESS_UNTYPED_PARENT_BITS: u8 = 28;
#[cfg(not(target_arch = "x86_64"))]
pub(crate) const PROCESS_UNTYPED_PARENT_BITS: u8 = 29;
pub(crate) const PROC_UNUSED: u8 = 0;
pub(crate) const PROC_RUNNABLE: u8 = 1;
pub(crate) const PROC_ZOMBIE: u8 = 2;
pub(crate) const PROC_WAITING: u8 = 3;
pub(crate) const PROC_VFS_WRITE: u8 = 4;
pub(crate) const PROC_VFS_READ: u8 = 5;
pub(crate) const PROC_SLEEPING: u8 = 6;
pub(crate) const PROC_VFS_ASYNC: u8 = 7;
pub(crate) const PROC_VFS_DEFERRED: u8 = 8;
pub(crate) const SERVICE_UNTYPED_BITS: u64 = 22;
pub(crate) const VFS_SERVICE_UNTYPED_BITS: u64 = 24;
pub(crate) const UART_SERVER_PID: u64 = 0xffff_0000;
pub(crate) const VFS_SERVER_PID: u64 = 0xffff_0001;
pub(crate) const CHILD_PRIORITY: u64 = 255;
pub(crate) const CHILD_MCP: u64 = 255;
pub(crate) const SBRK_EAGER: u64 = 1;
pub(crate) const SBRK_LAZY: u64 = 2;
pub(crate) const VM_ATTR_UNCACHED: u64 = 1 << 1;
pub(crate) const INIT_PATH: &[u8] = b"/ltp-wave1";

pub(crate) use linux_abi::{
    AT_BASE, AT_CLKTCK, AT_EGID, AT_ENTRY, AT_EUID, AT_EXECFN, AT_FDCWD, AT_FLAGS, AT_GID, AT_NULL,
    AT_PAGESZ, AT_PHDR, AT_PHENT, AT_PHNUM, AT_RANDOM, AT_REMOVEDIR, AT_SECURE, AT_UID, CLD_EXITED,
    CLOCK_MONOTONIC, CLOCK_REALTIME, CLONE_VM, CONSOLE_INO, DEVICE_MMIO_BASE, DEVICE_MMIO_SIZE,
    EAGAIN, EBADF, ECHILD, EEXIST, EFAULT, EINVAL, EIO, EISDIR, EMFILE, ENAMETOOLONG, ENOENT,
    ENOEXEC, ENOMEM, ENOSPC, ENOSYS, ENOTDIR, ENOTTY, EPERM, EPIPE, ERANGE, ESRCH, FileKind,
    HOST_REPLY_ENDPOINT_CPTR, IpcBadge, IpcProtocol, IpcStatus, LINUX_ABI_VERSION, LINUX_STAT_SIZE,
    MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, MAX_EXEC_ARG_LEN, MAX_EXEC_ARGS, MAX_FD, MAX_FILE_BYTES,
    MAX_IO_BYTES, MAX_OPEN_FILES, MAX_PATH_BYTES, O_ACCMODE, O_CLOEXEC, O_CREAT, O_DIRECTORY,
    O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, P_ALL, P_PID, PROT_EXEC, PROT_READ, PROT_WRITE,
    ROOT_INO, S_IFCHR, S_IFDIR, S_IFREG, SEEK_CUR, SEEK_END, SEEK_SET, SERVER_CNODE_CPTR,
    SERVER_RECV_REPLY_CPTR, SERVICE_ENDPOINT_CPTR, SHARED_BUFFER_PAGES, SHARED_BUFFER_VADDR,
    SIGCHLD, SYS_BRK, SYS_CHDIR, SYS_CLOCK_GETRES, SYS_CLOCK_GETTIME, SYS_CLOCK_NANOSLEEP,
    SYS_CLONE, SYS_CLONE3, SYS_CLOSE, SYS_DUP, SYS_DUP3, SYS_EXECVE, SYS_EXIT, SYS_EXIT_GROUP,
    SYS_FACCESSAT, SYS_FCNTL, SYS_FSTAT, SYS_FUTEX, SYS_GET_ROBUST_LIST, SYS_GETCWD,
    SYS_GETDENTS64, SYS_GETEGID, SYS_GETEUID, SYS_GETGID, SYS_GETPID, SYS_GETPPID, SYS_GETRANDOM,
    SYS_GETRUSAGE, SYS_GETTID, SYS_GETTIMEOFDAY, SYS_GETUID, SYS_IOCTL, SYS_KILL, SYS_LINKAT,
    SYS_LSEEK, SYS_MKDIRAT, SYS_MKNODAT, SYS_MMAP, SYS_MPROTECT, SYS_MREMAP, SYS_MUNMAP,
    SYS_NANOSLEEP, SYS_NEWFSTATAT, SYS_OPENAT, SYS_PIPE2, SYS_PPOLL, SYS_PRCTL, SYS_PRLIMIT64,
    SYS_PTRACE, SYS_READ, SYS_READLINKAT, SYS_READV, SYS_RT_SIGACTION, SYS_RT_SIGPROCMASK,
    SYS_RT_SIGRETURN, SYS_SCHED_YIELD, SYS_SET_ROBUST_LIST, SYS_SET_TID_ADDRESS, SYS_SOCKET,
    SYS_STATX, SYS_SYSINFO, SYS_TGKILL, SYS_TKILL, SYS_UMASK, SYS_UNAME, SYS_UNLINKAT, SYS_WAIT4,
    SYS_WAITID, SYS_WRITE, SYS_WRITEV, UART_ENDPOINT_CPTR, UART_MMIO_FRAME_VADDR,
    UART_REPLY_ENDPOINT_CPTR, UART0_MMIO_FRAME_BASE, UTS_LEN, VfsOp, WNOHANG, linux_exit_status,
    open_readable, open_writable, pack_stat_kind_nlink, unpack_stat_kind, unpack_stat_nlink,
    wants_write,
};

#[cfg(target_arch = "x86_64")]
pub(crate) use linux_abi::SYS_PAUSE;
